// נוצר אוטומטית ע"י scripts/fetch-images.mjs — אל תערכו ידנית
export const IMAGES: Record<string, string> = {
  "schonbrunn": "/images/schonbrunn.jpg",
  "hofburg": "/images/hofburg.jpg",
  "belvedere": "/images/belvedere.jpg",
  "stephansdom": "/images/stephansdom.jpg",
  "staatsoper": "/images/staatsoper.jpg",
  "khm": "/images/khm.png",
  "albertina": "/images/albertina.jpg",
  "leopold": "/images/leopold.jpg",
  "nhm": "/images/nhm.jpg",
  "prater": "/images/prater.jpg",
  "naschmarkt": "/images/naschmarkt.jpg",
  "cafe-central": "/images/cafe-central.jpg",
  "sacher": "/images/sacher.jpg",
  "demel": "/images/demel.jpg",
  "hundertwasser": "/images/hundertwasser.jpg",
  "karlskirche": "/images/karlskirche.jpg",
  "spanish-riding": "/images/spanish-riding.png",
  "stadtpark": "/images/stadtpark.jpg",
  "donauinsel": "/images/donauinsel.jpg",
  "kahlenberg": "/images/kahlenberg.jpg",
  "grinzing": "/images/grinzing.png",
  "haus-des-meeres": "/images/haus-des-meeres.jpg",
  "technisches-museum": "/images/technisches-museum.jpg",
  "zentralfriedhof": "/images/zentralfriedhof.jpg",
  "nationalbibliothek": "/images/nationalbibliothek.jpg",
  "graben": "/images/graben.jpg",
  "schonbrunn-zoo": "/images/schonbrunn-zoo.jpg",
  "musikverein": "/images/musikverein.jpg",
  "donauturm": "/images/donauturm.jpg",
  "rathaus": "/images/rathaus.jpg"
};
